### ISSUE TITLE
Add a sync version?

### ISSUE THREAD

**Issue by rauschma** [nodeca/probe-image-size#1]
For writing shell scripts in Node.js, I like the sync versions of tool functions. Maybe add one for probe-image-size?

**Comment by puzrin** [comment]
It's difficult to have both in singe project and keep code simple. At least, i have no time resources and motivation for such rewrite. Also, sync api doesn't seems to need partial load.

**Comment by puzrin** [comment]
Closing. With node 4+ thenify + co + yield is enougth.
