### ISSUE TITLE
Promise.prototype.then() not to spec

### ISSUE THREAD

**Issue by bchr02** [nodeca/probe-image-size#13]
Following the spec `Promise.prototype.then` should contain a second optional parameter `onRejected ` so one doesn't need to add a chained `catch()` but with probe-image-size it does not.

So, instead of being able to do this:
```javascript
probe(fileStream).then(dims => {
   ...
}, err => {
   ...
});
```
we are forced to do this:
```javascript
probe(fileStream).then(dims => {
   ...
}).catch( err => {
   ...
});
```

**Comment by puzrin** [comment]
- https://github.com/nodeca/probe-image-size/blob/3.0.0/index.js#L17
- https://github.com/nodeca/probe-image-size/blob/3.0.0/stream.js#L18

It returns a standard promise object. I think something is wrong at your side. Can you provide a minimal working test sample?

**Comment by bchr02** [comment]
Here you go:

```
git clone https://gist.github.com/bchr02/fb39ac10f527557b3222153e7dbe81e1
npm install
npm start
```

**Comment by bchr02** [comment]
I am getting `UnhandledPromiseRejectionWarning: Unhandled promise rejection`

**Comment by puzrin** [comment]
https://gist.githubusercontent.com/bchr02/fb39ac10f527557b3222153e7dbe81e1/raw/89f04bb3e07261f3945e20ce10e97b978bce36bf/server.js

If you use `.then(onSuccess, onFail)`, exceptions thrown from `onSuccess` handler are NOT handled in `onFail` handler. That's documented Promise behaviour and not related to this library. And that's a reason to use `.catch()` if you don't wish to get surprises.

Equal code of your example will be

```js
Promise.resolve().then(dims => {
    throw("there was an error");
}, err => {
    console.log("there was an error but it was handled");
});
```

**Comment by bchr02** [comment]
I should have realized this. I apologize for bothering you.

**Comment by puzrin** [comment]
No prob :). When good examples provided, it's not difficult to help.
