### ISSUE TITLE
404 status code with URL contains non English chars

### ISSUE THREAD

**Issue by sashberd** [nodeca/probe-image-size#15]
Hi

I`m working with Arabic/Hebrew pages and  I saw that if URL contains non English chars it is failed with 404 error.
For example try to check you application with http://www.pitria.com/wp-content/uploads/2017/08/אמא-סלפי1.jpg
Thanks

**Comment by puzrin** [comment]
I guess, you should percent-encode those and so on. This library does not make any magic about URLs, it just send what your provided. 404 means server returned "not found" for requested resource. That's not this library bug.

**Comment by sashberd** [comment]
So this solve all problem, Thanks
I suggest to add inside you code something like:
```
if (/[^\u0000-\u00ff]/.test(image.url)) {
                image.url=encodeURI(image.url)
            }
```
This will improve you code coverage
FYA

**Comment by puzrin** [comment]
That will not help if url has query part. I'd prefer to avoid magic that can fail.
