### ISSUE TITLE
readme typo?

### ISSUE THREAD

**Issue by CanRau** [nodeca/probe-image-size#25]
shouldn't this read `probe.sync(src)`?
https://github.com/nodeca/probe-image-size#syncprobesrc---resultnull

**Comment by puzrin** [comment]
No https://github.com/nodeca/probe-image-size/blob/master/index.js#L51

**Comment by CanRau** [comment]
interesting & fast! 👍

**Comment by puzrin** [comment]
Ah, my bad, i see that default async call is named as "probe", because of `var probe = require('probe-image-size')`. From this point of view, you are right. But i think expanding this practice to `probe.sync` will add even more confusion. Need better ideas.

**Comment by CanRau** [comment]
nice, you figured out what confused me :D
