### ISSUE TITLE
Dimensions wrong if image orientation isn't default

### ISSUE THREAD

**Issue by designbyadrian** [nodeca/probe-image-size#26]
The results from width/height are swapped if the image is rotated. Any plans of reading the EXIF data of an image to remedy this issue?

**Comment by puzrin** [comment]
Sorry, deep jpeg parse is currently out of this package scope. Orientation is not required everytime. If you need orientation, you should use extra libs. Here is example of code we use in own projects:

https://github.com/nodeca/nodeca.users/blob/4039626af0728229f58b80d8c9e5bab7efda2af5/client/users/avatar/change/change.js#L463-L469
