### ISSUE TITLE
In browser?

### ISSUE THREAD

**Issue by tomgallagher** [nodeca/probe-image-size#29]
Hey

I'd like to use this in the browser as a standalone package? Is this possible?

Thanks

**Comment by puzrin** [comment]
Yes, you can browserify it, or any sub-component you need.

**Comment by tomgallagher** [comment]
OK. Never had much luck with browserify. I'm not that worried about backwards compatibility , so maybe using the new [Streams API ](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams#Consuming_a_fetch_as_a_stream)might be a place to start. And look at porting in stream parsers for image types. I'll have a look.

**Comment by ChrisMagnuson** [comment]
It would be nice if this was reopend to
