### ISSUE TITLE
request package is deprecated, consider replacing with an alternative like node-fetch

### ISSUE THREAD

**Issue by polarathene** [nodeca/probe-image-size#40]
[The `request` package has been deprecated](https://github.com/request/request/issues/3142). This package only seems to use it in the `http.js` file, the advice appears to migrate to an alternative like `node-fetch`.

https://github.com/nodeca/probe-image-size/blob/7d7e4a91d232d2d6fca2339df61432e3c415b0b8/http.js#L38

https://github.com/nodeca/probe-image-size/blob/7d7e4a91d232d2d6fca2339df61432e3c415b0b8/http.js#L57

I'm not raising the issue due to any bug or vulnerabilities, just making you aware of the deprecation as it is raised as a warning during package installs:

```
warning gatsby-plugin-sharp > probe-image-size > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

Cheers.

**Comment by konsumer** [comment]
If [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) were used, it might even work on client-side code which would be amazing, instead of this:

```
error - ./node_modules/request/lib/har.js:3:0
Module not found: Can't resolve 'fs'
```

**Comment by puzrin** [comment]
MEMO: https://github.com/tomas/needle looks promissing. Others has suspicious issues in tracker or lack of features.

**Comment by puzrin** [comment]
https://github.com/nodeca/probe-image-size/commit/40f0968732808dcacfb1000b250e0d278c388727

Switched to `needle`
