### ISSUE TITLE
Version without fs  dependency?

### ISSUE THREAD

**Issue by styxlab** [nodeca/probe-image-size#41]
Thanks a lot for this nice package!

Would it be possible for you to make a version without `fs` dependency? If you probe image size from an `url` stream, you don't need `fs`. Currently I cannot use this package in serverless lambda functions because of this dependency. The package `buffer-image-size` is a good example of a similar approach without `fs`.

Thanks for your consideration.

**Comment by puzrin** [comment]
This package has no fs depenency

**Comment by hoanghiep** [comment]
@puzrin 

https://github.com/tomas/needle/blob/d2909e2a5f89ceeff0c29320d3a045afe47b2638/lib/multipart.js

fs has been used by needle (multipart). 

How can i use this package in client side?

**Comment by puzrin** [comment]
@hoanghiep node.js downloader can no work on client for obvious reasons. I would suggest to 'reqiure' sync part only, download full file and use sync method.
