### ISSUE TITLE
How does this library work?

### ISSUE THREAD

**Issue by agcty** [nodeca/probe-image-size#43]
How does this library work as in what's the technical background behind it and not how you use it?

I'd love to understand how that library works behind the scenes but I'm having some difficulties understanding what's going on in the source code. Can anybody shed a little light on this? 🤗

**Comment by puzrin** [comment]
Sorry, due time constrains, can't participate in generic programming talks. May be, if you ask something more concrete, i could try to explain. Start with reading sources of sync method, those are trivial.

**Comment by agcty** [comment]
Alright, perfectly understand!

My main question is where do you actually get the information from? From the header of the remote source?

**Comment by puzrin** [comment]
If you ask about remote images - information is taken from remote source. It does not depends on extension, mime type and so on. Downloads stars and is immediately tested by multiple parsers in parallel https://github.com/nodeca/probe-image-size/tree/master/lib/parse_stream.

Each parser needs very few data to decide it it succeeds or fail. So, when each got decision - download is terminated and joined decision is returned.

That's a principal difference with other solutions - no need to load full source into memory.

If you need to understand, what exactly is tested - see sync variant, it does he same, but looks much more simple https://github.com/nodeca/probe-image-size/tree/master/lib/parse_sync

**Comment by agcty** [comment]
@puzrin ah i see! thank you very much for your explanation!
