### ISSUE TITLE
Broken test in node v14

### ISSUE THREAD

**Issue by puzrin** [nodeca/probe-image-size#44]
https://github.com/nodejs/node/issues/35926

Node 14 has regression, failing to interrupt download early. We still can make release with skipped test.

**Comment by styxlab** [comment]
I am using `probe-image-size` within a Next.js project and identified the package to cause flaky build errors. In the error case, the async `probe()` never returns and the client finally gives up. This very much looks like the error reported here (I am running on node v14.15.1).

Do you know of a possible workaround? Is it possible to substitute `push(null)` with something else that ensures the stream is properly terminated? When do you expect the fix to land in `node v14`?

**Comment by puzrin** [comment]
First, try node 15 (it's fixed) to be sure your problems are caused by this bug.

All info about LTS is by link, i can't add more, also waiting for release.

**Comment by styxlab** [comment]
Thanks a lot for the prompt reply. Unfortunately my problem is not solved with v15.2.1, so it must be something else. I may open another issue here. Before, I need to make some more tests in order to verify that the server that is serving the image is not the problem.

**Comment by puzrin** [comment]
Fixed in 14.15.2
