### ISSUE TITLE
Unrecognized FIle Format Error

### ISSUE THREAD

**Issue by Surajsdalvi** [nodeca/probe-image-size#47]
Hi,

I want dimension of following attached Image. But it giving me following error:

` ProbeError: unrecognized file format`
`name: 'ProbeError',`
`message: 'unrecognized file format',`
` code: 'ECONTENT' }`

here is my code

`var probe = require('probe-image-size');
var fs = require('fs')

return probe('https://images.contentstack.io/v3/assets/blt37054b6140c1853d/bltdcad91c964a7688a/5fc6577a09ed4c6f277f1b2d/dleta.jpeg').then(function (result) {
    console.log("Done",result)
}).catch(function (error) {
    console.log("Error",error)
})`

Kindly help me here.

![guard-buckingham-200x300_(1)](https://user-images.githubusercontent.com/11155458/100759018-29ca9800-3416-11eb-9944-8c49208097ea.jpeg)

**Comment by puzrin** [comment]
That image can not be opened in browser, because is broken => nothing to fix.

**Comment by surajdalvi1** [comment]
can you please it using the following URL: https://images.contentstack.io/v3/assets/blt37054b6140c1853d/blt6a24f920cbd20206/5fc67269bfc5dd7188661119/sample.jpeg

**Comment by puzrin** [comment]
I did that. In FireFox 83 & Chomium 86. Both can not open image.
