### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by TangF** [nodeca/probe-image-size#49]
hi,here is my code.
`probe('https://obs-xy-test.obs.cn-east-2.myhuaweicloud.com/5807ad7a07bc4a26a1f4b22d4a33f218.jpeg')
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });`

error:TypeError: NetworkError when attempting to fetch resource.
browser:FireFox 84.0.1

**Comment by puzrin** [comment]
Network part is for nodejs and can not be browserified.
