### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by Kodiakkb** [nodeca/probe-image-size#50]
Hello, our customers upload more and more HEIC pictures from their phones. Will this format be supported in a future version?
![heic](https://user-images.githubusercontent.com/3121549/105472560-61c6bc80-5c9c-11eb-9589-c4afa61d5dec.jpg)

**Comment by puzrin** [comment]
Only if someone decides to propose PR (as been done for ICO). We do not accept format demands, sorry.
