### ISSUE TITLE
dist is too big!

### ISSUE THREAD

**Issue by wxfred** [nodeca/probe-image-size#51]
I create a vue cli3 program with `webpack-bundle-analyzer` installing.
The chunk-vendors.js is up to 1.16M after import `probe-image-size` package while the origin chunk-vendors.js is 110.23KB.
I test another package `image-size` which is mentioned in your readme file, the final chunk-vendors.js is 155.47KB.

After import  `probe-image-size`, `webpack-bundle-analyzer` shows there are a lot of packages using the same package `bn.js`. That's weird.

**Comment by wxfred** [comment]
Both 5.0.0 and 6.0.0 have the same problem.
![probe-image-size-chunk-vendors](https://user-images.githubusercontent.com/6032500/105640175-7493e980-5e74-11eb-920f-8c475dd8d042.png)

**Comment by puzrin** [comment]
This module has server-specific code. You can try to requie only sync part.
