### ISSUE TITLE
it will last forever if probe a link to a pdf file

### ISSUE THREAD

**Issue by dukemai** [nodeca/probe-image-size#56]
We accidently found a problem when our users choose a pdf file and the logic using probe running forever with this file. it is of course that we should validate but it is a case that can cause forever running. I think we might need timeout to handle this case also.

**Comment by puzrin** [comment]
Please provide step-by-step example how to reproduce

**Comment by puzrin** [comment]
Closing as stale. This may be network problem. Please provide more info how to reproduce, to reopen.
