### ISSUE TITLE
Improve parser ordering to speed up probe

### ISSUE THREAD

**Issue by styxlab** [nodeca/probe-image-size#65]
@puzrin Thanks so much for this great package that I seem to be coming back to!

Just wondering if you could optimize the performance by changing the loop order over all formats (currently in alphabetical order), see

- https://github.com/nodeca/probe-image-size/blob/c9f38c12f61568f7d30cff2bf85b2559c7a70507/sync.js#L10
- https://github.com/nodeca/probe-image-size/blob/c9f38c12f61568f7d30cff2bf85b2559c7a70507/stream.js#L42

I understand that the file name or extension does not a guarantee that the image is of that format. Here is my suggestion:

- allow for an option to pass in the format (e.g. 'jpeg') and ensure that format is parsed first (user hint)
- change the alphabetical parser order based on the image format distribution on the web (higher probability of parsing common formats first)

Thanks a lot for the consideration!

**Comment by puzrin** [comment]
I don't like optimizations "just for fun". Do you have some concrete metrics to prove real problems with speed?

**Comment by puzrin** [comment]
Closed (no reasonable proofs)
