### ISSUE TITLE
Desn't work with NextJS `getStaticProps`

### ISSUE THREAD

**Issue by maximousblk** [nodeca/probe-image-size#69]
I'm trying to use `probe-image-size` for getting image dimensions to use NextJS' `<Image />` component. It works in dev (`next dev`) but throws the following error in prod (`next build`)

![image](https://user-images.githubusercontent.com/28438021/143180917-7efe9fd3-43b1-4566-ba43-8ac82ee766c9.png)

Any way to get around this?

**Comment by puzrin** [comment]
You can not use needle in browser (and can not fetch images from any domain, due securuty policy). If you need to analyze binary data - use `/sync.js` only.

**Comment by maximousblk** [comment]
@puzrin can you please give me an example of how to do that

here's the code where I want to use it: 

https://github.com/maximousblk/maximousblk.me/blob/2595c2f3656b8d016f27419e82cea8a00b39ed4b/lib/notion.ts#L144-L148

**Comment by maximousblk** [comment]
nevermind, I figured it out: https://github.com/maximousblk/maximousblk.me/blob/41661f38e7403e4361237384e0cd62eab681e64c/lib/notion.ts#L144-L147
