### ISSUE TITLE
Sync Usage?

### ISSUE THREAD

**Issue by ankurhora** [nodeca/probe-image-size#7]
Hey.. i need to implement this with sync 
how to use the snippet provided in the readme.?

**Comment by puzrin** [comment]
See last sync call in example.

**Comment by ankurhora** [comment]
It says unresolved variable or type sync.. 
i am implement it in nodejs.
Please can to elaborate the implementation

**Comment by puzrin** [comment]
https://github.com/nodeca/probe-image-size/blob/master/test/sync.js tests are ok. Please, provide code example, how to reproduce your problem.

**Comment by ankurhora** [comment]
thumbnails.each(function(j, thum) {
			try {
				var tempUrls = $(thum).attr("src");
				var size ;
				var temp = "http:"+tempUrls.replace(/\'/g, "");

				var res = sync.probe(temp);


		}
			catch(e) {	}
		});



here thumbnails is array of img tags

**Comment by puzrin** [comment]
```js
var probe = require('probe-image-size');
probe.sync(data)
```

https://github.com/nodeca/probe-image-size#example

**Comment by ankurhora** [comment]
This returns null.. 
but this
probe('http://example.com/image.jpg', function (err, result) {
  console.log(result); 
});
works fine

P.S data passed in this should be a url right ?

**Comment by puzrin** [comment]
Sync version needs arrays. Could you read the readme docs and examples prior to ask questions? Those are very short.

**Comment by ankurhora** [comment]
i have read them before hand... also array is been already passed as per documentation but there isnt much example

**Comment by ankurhora** [comment]
I think the solution u provided
probe.sync(data);
Which is last of the examples
Requires reading from a buffer.. whereas the solution I  need is to read from url but it should be sync
What is I think I need is 
Sync.probe(src)->result|null
But unable to understand the usage

**Comment by puzrin** [comment]
It's technically impossible to use url and sync method in the same time.

**Comment by ankurhora** [comment]
Is there a work around? Or I have to switch the method of use

**Comment by puzrin** [comment]
No workarounds possible. You should use async method (with callback or promise) if you need to get image info by url..

**Comment by ankurhora** [comment]
Async method is not suitable for me.. have used producer/consumer solution too..  I need the information of each url ( maybe 20 sometime) and pass it to the scrapper ( using appFarm nodejs scrapper) but it doesnot wait for the result to process and ends before the dimentions processed

**Comment by puzrin** [comment]
I can't help you with programming, sorry.

**Comment by ankurhora** [comment]
Found a workaround using  'deasync'.
Thanks anyways
