### ISSUE TITLE
Exception in /lib/common.js missing stream module?

### ISSUE THREAD

**Issue by bankadams** [nodeca/probe-image-size#70]
The line:
`var Transform    = require('stream').Transform;`
is returning undefined.
....
...
The following line thus throws an exception 
// Inherit from Transform
`ParserStream.prototype = Object.create(Transform.prototype);`
.....

ERROR thrown:

common.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')

**Comment by puzrin** [comment]
See tests. Those are ok.

**Comment by tlyon3** [comment]
What tests are you referring to? I'm trying to utlize this package and it just crashes because it's undefined.

**Comment by puzrin** [comment]
https://github.com/nodeca/probe-image-size/tree/master/test

**Comment by kmdinake** [comment]
@tlyon3 did you manage to resolve this issue?

**Comment by pramodAmbekar** [comment]
Hi Team,
Did you manage to resolve this issue?
