### ISSUE TITLE
Undefined issues with react-scripts 5 / CRA 5.0 

### ISSUE THREAD

**Issue by FrancoMuniz** [nodeca/probe-image-size#72]
I just updated my create-react-app application to 5.0, but it's causing some libraries to stop working. I guess probe-image-size is used in plotly.js, which is what I use for charts.

When starting my application, I get the following error on the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object../node_modules/probe-image-size/lib/common.js
```

Any ideas on how to fix it? Thanks a lot!

**Comment by puzrin** [comment]
Sorry, can't help with outer apps. If you insist on bug in this package, please provide a minimal sample (without react and so on)

**Comment by FrancoMuniz** [comment]
> 

Sorry I didn't get what you mean. The issue is happening inside this module, here's an image:
![image](https://user-images.githubusercontent.com/37410203/155583154-743a04c1-9018-4b5b-a378-fcdaac393cb0.png)

**Comment by FrancoMuniz** [comment]
Seems to be a general issue with CRA since the latest update. Will ask there, thanks! Sorry for the inconvenience.

**Comment by kmdinake** [comment]
@FrancoMuniz did you manage to resolve this issue?
